### ISSUE TITLE
page not found 404-BUG

### ISSUE THREAD

**Issue by im-ysh** [VGandhi27/FoodWebApp#27]
hi @VGandhi27 . i see that when i click on your live project url . it shows "page not found'' 404 error message. website is not loading i would love to work on this issue.Please assign this to me. I am a gssoc contributor.Thank you.

**Comment by simitnamdev027** [comment]
hello @VGandhi27 the official link which is provided in the repo is broken , i would like to work on this issue

**Comment by Kbageja** [comment]
Hello @VGandhi27   the link is broken it has to be redeployed , i would like to work on this issue , please assign this to me
